# Generated by Django 4.2.4 on 2023-08-22 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_account_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_matematica', models.FloatField(default=0)),
                ('media_ciencias_natureza', models.FloatField(default=0)),
                ('media_linguagens', models.FloatField(default=0)),
                ('media_ciencias_humanas', models.FloatField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
