# Generated by Django 4.2.4 on 2023-08-25 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_mediageral_data_calculada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediageral',
            options={'verbose_name_plural': 'Medias Gerais'},
        ),
        migrations.AlterField(
            model_name='mediageral',
            name='data_calculada',
            field=models.DateField(auto_now_add=True),
        ),
    ]
