version: '3.9'
services:
  redis:
    image: redis:alpine
    container_name: redis

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: postgres_db  
    env_file:
      - .env
  app:
    build: .
    volumes:
      - ./app:/app
      - ./scripts/:/scripts
    ports:
      - 8000:8000
    image: app:django
    container_name: django_app
    depends_on:
      - db
    env_file:
      - .env
  celery:
    restart: always
    container_name: celery1
    build:
      context: .
      # DEBUG ONLY FOR DEVELOPMENT
    command: celery -A enem10x worker -l DEBUG
    volumes:
      - ./app:/app
    depends_on:
      - db
      - redis
      - app

volumes:
  postgres_data:

