version: "3.9"



services:
  redis:
    image: redis:alpine
    container_name: redis
    deploy:
      resources:
        limits:
          memory: 500m
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf

  db-master:
    image: postgres:15
    ports:
      - target: 5432
        published: 5433
        protocol: tcp
        mode: host
    environment:
      POSTGRES_DB: enem
      POSTGRES_USER: roberto
      POSTGRES_PASSWORD: Dulce2014
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./master:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm

    container_name: postgres_db_master

  db-replication-1:
    image: postgres:15
    ports:
      - target: 5432
        published: 5434
        protocol: tcp
        mode: host
    environment:
      POSTGRES_DB: enem
      POSTGRES_USER: repuser
      POSTGRES_PASSWORD: repuser
      POSTGRES_HOST: db-replication-1
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./replication:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm

    container_name: postgres_db_replication_1

  app:
    build: .
    volumes:
      - ./app:/app
      - ./scripts/:/scripts
      - questoes_data:/data/media/questoes
    ports:
      - 8000:8000
    image: app:django
    container_name: django_app
    depends_on:
      - db-master
    env_file:
      - .env

  celery:
    restart: always
    container_name: celery1
    build:
      context: .
      # DEBUG ONLY FOR DEV
    command: celery -A enem10x worker -l info
    volumes:
      - ./app:/app
    depends_on:
      - db-master
      - redis
      - app
      - db-replication-1

volumes:
  questoes_data: