version: '3.9'
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: postgres_db  
    env_file:
      - .env
  app:
    build: .
    volumes:
      - ./app:/app
      - ./scripts/:/scripts
    ports:
      - 8000:8000
    image: app:django
    container_name: django_app
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:

