# Generated by Django 4.2.4 on 2023-08-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_aluno',
            field=models.BooleanField(default=True, verbose_name='Aluno'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='ADM'),
        ),
    ]
