# Generated by Django 4.2.4 on 2023-08-22 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import materiais.funcs


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=10)),
                ('peso', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Niveis',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='SubMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('materia', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='materiais.materia')),
            ],
            options={
                'verbose_name_plural': 'Sub Materias',
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField(default=None, null=True)),
                ('imagem', models.ImageField(blank=True, default=None, null=True, upload_to=materiais.image.define_image_path_questoes)),
                ('opcoes', models.JSONField(null=True)),
                ('opcao_correta', models.IntegerField(blank=True, default=None, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('linguagens', 'Linguagens e suas Tecnologias'), ('matematica', 'Matemática e suas Tecnologias'), ('natureza', 'Ciências da Natureza'), ('humanas', 'Ciências Humanas')], default=None, max_length=50, null=True)),
                ('conteudo', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='materiais.conteudo')),
                ('nivel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='materiais.nivel')),
            ],
            options={
                'verbose_name_plural': 'Questoes',
            },
        ),
        migrations.CreateModel(
            name='ProvaRespondida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.IntegerField(default=None, null=True)),
                ('acerto', models.BooleanField(blank=True, default=None, null=True)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='materiais.questao')),
            ],
        ),
        migrations.CreateModel(
            name='ProvaCompleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(default=0)),
                ('acertos', models.IntegerField(default=0)),
                ('erros', models.IntegerField(default=0)),
                ('ranking_piores_conteudos', models.JSONField(blank=True, default=None, null=True)),
                ('ranking_melhores_conteudos', models.JSONField(blank=True, default=None, null=True)),
                ('data_feita', models.DateTimeField(auto_now_add=True)),
                ('acerto_dificuldade', models.JSONField(null=True)),
                ('tipos', models.JSONField(null=True)),
                ('respostas', models.ManyToManyField(to='materiais.provarespondida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='conteudo',
            name='sub_materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='materiais.submateria'),
        ),
    ]
