# Generated by Django 4.2.4 on 2023-08-23 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0002_remove_provacompleta_respostas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provacompleta',
            name='tipos',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='questao',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='materiais.nivel'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='opcao_correta',
            field=models.IntegerField(default=None),
        ),
    ]
