# Generated by Django 4.2.4 on 2023-08-23 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0003_alter_provacompleta_tipos_alter_questao_nivel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provarespondida',
            name='resposta',
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='questao',
            name='nivel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='materiais.nivel'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='opcao_correta',
            field=models.CharField(default=None, max_length=1),
        ),
    ]
