# Generated by Django 4.2.4 on 2023-08-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0004_alter_provarespondida_resposta_alter_questao_nivel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudo',
            name='nome',
            field=models.CharField(max_length=150),
        ),
    ]
