# Generated by Django 4.2.4 on 2023-08-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0006_alter_conteudo_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='conteudo',
        ),
        migrations.AddField(
            model_name='questao',
            name='conteudo',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='questoes', to='materiais.conteudo'),
        ),
    ]
