# Generated by Django 4.2.4 on 2023-08-30 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0011_provarespondida_simulado_simulado_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulado',
            name='materia',
            field=models.ManyToManyField(blank=True, default=None, to='materiais.materia'),
        ),
    ]
