# Generated by Django 4.2.4 on 2023-09-06 03:31

from django.db import migrations, models
import django.db.models.deletion
import materiais.funcs


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0013_questao_indentificador_unico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questao',
            old_name='imagem',
            new_name='imagem_enunciado',
        ),
        migrations.CreateModel(
            name='OpcaoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_a', models.ImageField(blank=True, default=None, null=True, upload_to=materiais.funcs.define_image_path)),
                ('imagem_b', models.ImageField(blank=True, default=None, null=True, upload_to=materiais.funcs.define_image_path)),
                ('imagem_c', models.ImageField(blank=True, default=None, null=True, upload_to=materiais.funcs.define_image_path)),
                ('imagem_d', models.ImageField(blank=True, default=None, null=True, upload_to=materiais.funcs.define_image_path)),
                ('imagem_e', models.ImageField(blank=True, default=None, null=True, upload_to=materiais.funcs.define_image_path)),
                ('questao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='materiais.questao')),
            ],
        ),
    ]
