# Generated by Django 4.2.4 on 2023-09-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0014_rename_imagem_questao_imagem_enunciado_opcaoimagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questao',
            old_name='indentificador_unico',
            new_name='identificador_unico',
        ),
    ]
