# Generated by Django 4.2.4 on 2023-09-06 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0015_rename_indentificador_unico_questao_identificador_unico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcaoimagem',
            options={'verbose_name_plural': 'Opcoes com imagem'},
        ),
    ]
