# Generated by Django 4.2.4 on 2023-09-10 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0017_remove_provacompleta_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcaoimagem',
            name='questao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes_imagem', to='materiais.questao'),
        ),
    ]
