# Generated by Django 4.2.4 on 2023-09-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0018_alter_opcaoimagem_questao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvaCriadaProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questao', models.ManyToManyField(to='materiais.questao')),
            ],
        ),
    ]
