# Generated by Django 4.2.4 on 2023-09-11 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0022_alter_submateria_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudo',
            name='sub_materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conteudo', to='materiais.submateria'),
        ),
    ]
