# Generated by Django 4.2.4 on 2023-09-11 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0024_alter_questao_enunciado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='identificador_unico',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
