# Generated by Django 4.2.4 on 2023-09-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0025_alter_questao_identificador_unico'),
    ]

    operations = [
        migrations.AddField(
            model_name='provacompleta',
            name='porcentagem_acerto',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
