# Generated by Django 4.2.4 on 2023-09-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0026_provacompleta_porcentagem_acerto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provacompleta',
            name='acerto_dificuldade',
            field=models.JSONField(blank=True, default=0, null=True),
        ),
    ]
