# Generated by Django 4.2.4 on 2023-09-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0027_alter_provacompleta_acerto_dificuldade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provacompleta',
            name='acerto_dificuldade',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='provacompleta',
            name='porcentagem_acerto',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
