# Generated by Django 4.2.4 on 2023-09-17 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0028_alter_provacompleta_acerto_dificuldade_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tipo',
        ),
        migrations.AddField(
            model_name='provacompleta',
            name='simulado',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='materiais.simulado'),
        ),
    ]
