# Generated by Django 4.2.4 on 2023-09-17 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0029_delete_tipo_provacompleta_simulado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provacompleta',
            name='nota',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='provacompleta',
            name='simulado',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='materiais.simulado'),
        ),
    ]
