# Generated by Django 4.2.4 on 2023-09-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0030_alter_provacompleta_nota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='proporcao',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Propocao pré-definida para este contéudo para provas.', max_digits=3),
        ),
    ]
