# Generated by Django 4.2.4 on 2023-09-25 23:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0031_conteudo_proporcao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conteudo',
            name='proporcao',
        ),
        migrations.CreateModel(
            name='GrupoConteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proporcao', models.DecimalField(decimal_places=2, default=0.0, help_text='Propocao pré-definida para este contéudo para provas.', max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('conteudos', models.ManyToManyField(limit_choices_to={'sub_materia__materia': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiais.materia')}, to='materiais.conteudo')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiais.materia')),
            ],
        ),
    ]
