# Generated by Django 4.2.4 on 2023-09-26 22:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0033_alter_grupoconteudo_conteudos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoconteudo',
            name='conteudos',
            field=models.ManyToManyField(blank=True, null=True, to='materiais.conteudo'),
        ),
        migrations.AlterField(
            model_name='grupoconteudo',
            name='proporcao',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Propocao pré-definida para este contéudo para provas.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
