# Generated by Django 4.2.4 on 2023-09-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0034_alter_grupoconteudo_conteudos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoconteudo',
            name='conteudos',
            field=models.ManyToManyField(blank=True, to='materiais.conteudo'),
        ),
    ]
