# Generated by Django 4.2.4 on 2023-10-04 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0036_alter_grupoconteudo_conteudos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nivel',
            name='peso',
        ),
    ]
