# Generated by Django 4.2.4 on 2023-10-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0037_remove_nivel_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivel',
            name='nivel',
            field=models.IntegerField(),
        ),
    ]
