# Generated by Django 4.2.4 on 2023-10-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0038_alter_nivel_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoconteudo',
            name='conteudos',
            field=models.ManyToManyField(blank=True, null=True, related_name='grupo', to='materiais.conteudo'),
        ),
    ]
