# Generated by Django 4.2.4 on 2023-10-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0039_alter_grupoconteudo_conteudos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoconteudo',
            name='conteudos',
            field=models.ManyToManyField(blank=True, related_name='grupo', to='materiais.conteudo'),
        ),
    ]
