# Generated by Django 4.2.4 on 2023-12-13 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0041_remove_questao_enunciado'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='data_adicionada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
