# Generated by Django 4.2.4 on 2023-12-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0042_questao_data_adicionada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provacompleta',
            name='nota',
        ),
        migrations.AddField(
            model_name='simulado',
            name='valor',
            field=models.FloatField(default=0, null=True),
        ),
    ]
