# Generated by Django 4.2.4 on 2023-08-27 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_mediageral_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediageral',
            name='data_calculada',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
