# Generated by Django 4.2.4 on 2023-08-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_mediageral_data_calculada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cpf',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
