# Generated by Django 4.2.4 on 2023-08-31 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_mediageral_media_ciencias_humanas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_calculada', models.DateField(default=django.utils.timezone.now, null=True)),
                ('nota_matematica', models.FloatField(blank=True, default=None, null=True)),
                ('nota_ciencias_natureza', models.FloatField(blank=True, default=None, null=True)),
                ('nota_linguagens', models.FloatField(blank=True, default=None, null=True)),
                ('nota_ciencias_humanas', models.FloatField(blank=True, default=None, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Medias Gerais',
            },
        ),
        migrations.DeleteModel(
            name='MediaGeral',
        ),
    ]
