# Generated by Django 4.2.4 on 2023-08-31 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_notas_delete_mediageral'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notas',
            options={'verbose_name_plural': 'Notas provas'},
        ),
        migrations.CreateModel(
            name='MediaGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atualizada', models.DateTimeField(auto_now=True)),
                ('media_matematica', models.FloatField(blank=True, default=None, null=True)),
                ('media_ciencias_natureza', models.FloatField(blank=True, default=None, null=True)),
                ('media_linguagens', models.FloatField(blank=True, default=None, null=True)),
                ('media_ciencias_humanas', models.FloatField(blank=True, default=None, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Media Geral',
            },
        ),
    ]
