# Generated by Django 4.2.4 on 2023-09-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_account_is_professor_alter_account_is_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verificado'),
        ),
    ]
