# Generated by Django 4.2.4 on 2023-09-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_aluno_professor_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='alunos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='total_alunos',
            field=models.IntegerField(default=400),
            preserve_default=False,
        ),
    ]
