# Generated by Django 4.2.4 on 2023-09-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_aluno_professor_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='professores',
            field=models.ManyToManyField(related_name='turmas', to='usuarios.professor'),
        ),
    ]
