# Generated by Django 4.2.4 on 2023-09-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_alter_turma_professores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='alunos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='professor',
            name='total_alunos',
            field=models.IntegerField(default=60),
        ),
    ]
