# Generated by Django 4.2.4 on 2023-09-03 13:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_alter_professor_alunos_alter_professor_total_alunos'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='codigo',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
