# Generated by Django 4.2.4 on 2023-09-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_turma_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediageral',
            name='media_ciencias_humanas',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mediageral',
            name='media_ciencias_natureza',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mediageral',
            name='media_linguagens',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mediageral',
            name='media_matematica',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
