# Generated by Django 4.2.4 on 2023-09-11 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_prova_pra_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(blank=True, default=None, to='usuarios.aluno'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='criador',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criador_turma', to='usuarios.professor'),
        ),
    ]
