# Generated by Django 4.2.4 on 2023-09-11 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0024_alter_questao_enunciado'),
        ('usuarios', '0023_alter_turma_alunos_alter_turma_criador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prova_pra_turma',
            name='prova',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prova_pra_turma', to='materiais.provacriadaprofessor'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='professores',
            field=models.ManyToManyField(blank=True, default=None, related_name='turmas', to='usuarios.professor'),
        ),
    ]
