# Generated by Django 4.2.4 on 2023-09-17 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0027_alter_provacompleta_acerto_dificuldade'),
        ('usuarios', '0024_alter_prova_pra_turma_prova_alter_turma_professores'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvaTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alunos', models.ManyToManyField(related_name='prova_turma', to='usuarios.aluno')),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prova_pra_turma', to='materiais.provacriadaprofessor')),
            ],
        ),
        migrations.CreateModel(
            name='RankingConteudosErrados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo_1', models.CharField(blank=True, max_length=150, null=True)),
                ('conteudo_2', models.CharField(blank=True, max_length=150, null=True)),
                ('conteudo_3', models.CharField(blank=True, max_length=150, null=True)),
                ('conteudo_4', models.CharField(blank=True, max_length=150, null=True)),
                ('conteudo_5', models.CharField(blank=True, max_length=150, null=True)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.aluno')),
                ('materia', models.ManyToManyField(to='materiais.materia')),
            ],
        ),
        migrations.DeleteModel(
            name='Prova_pra_Turma',
        ),
    ]
