# Generated by Django 4.2.4 on 2023-09-17 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0026_remove_rankingconteudoserrados_conteudo_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediageral',
            name='usuario',
        ),
        migrations.AddField(
            model_name='mediageral',
            name='aluno',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='usuarios.aluno'),
        ),
    ]
