# Generated by Django 4.2.4 on 2023-09-18 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0030_alter_provacompleta_nota_and_more'),
        ('usuarios', '0028_alter_mediageral_aluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rankingconteudoserrados',
            name='conteudos',
        ),
        migrations.AddField(
            model_name='rankingconteudoserrados',
            name='conteudo_1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rce_conteudo_1', to='materiais.conteudo'),
        ),
        migrations.AddField(
            model_name='rankingconteudoserrados',
            name='conteudo_2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rce_conteudo_2', to='materiais.conteudo'),
        ),
        migrations.AddField(
            model_name='rankingconteudoserrados',
            name='conteudo_3',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rce_conteudo_3', to='materiais.conteudo'),
        ),
        migrations.AddField(
            model_name='rankingconteudoserrados',
            name='conteudo_4',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rce_conteudo_4', to='materiais.conteudo'),
        ),
        migrations.AddField(
            model_name='rankingconteudoserrados',
            name='conteudo_5',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rce_conteudo_5', to='materiais.conteudo'),
        ),
    ]
