# Generated by Django 4.2.4 on 2023-09-25 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0029_remove_rankingconteudoserrados_conteudos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rankingconteudoserrados',
            options={'verbose_name_plural': 'Ranking Conteudo Errados'},
        ),
    ]
