# Generated by Django 4.2.4 on 2023-12-15 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0030_alter_rankingconteudoserrados_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='usuario',
        ),
        migrations.AddField(
            model_name='notas',
            name='aluno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.aluno'),
        ),
    ]
