# Generated by Django 4.2.4 on 2023-12-16 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0031_remove_notas_usuario_notas_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='aluno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='usuarios.aluno'),
        ),
    ]
