# Generated by Django 4.2.4 on 2023-12-28 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0033_escola_cordernadorescola_turma_escola'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='cordernador',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.cordernadorescola'),
        ),
    ]
