# Generated by Django 4.2.4 on 2023-08-20 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0002_alter_nivel_peso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nivel',
            options={'verbose_name_plural': 'Niveis'},
        ),
        migrations.AlterModelOptions(
            name='questoes',
            options={'verbose_name_plural': 'Questoes'},
        ),
        migrations.RemoveField(
            model_name='questoes',
            name='chave',
        ),
    ]
