# Generated by Django 4.2.4 on 2023-08-21 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0004_questoes_opcao_correta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='QuestoesProva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiais.questoes')),
            ],
            options={
                'verbose_name_plural': 'Questoes escolhidas pra prova',
            },
        ),
        migrations.CreateModel(
            name='ProvaRespondida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acerto', models.BooleanField()),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='materiais.questoesprova')),
            ],
        ),
        migrations.AddField(
            model_name='questoes',
            name='conteudo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='materiais.conteudo'),
        ),
    ]
