# Generated by Django 4.2.4 on 2023-08-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0005_alter_conteudo_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudo',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
