# Generated by Django 4.2.4 on 2023-08-21 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materiais', '0005_conteudo_questoesprova_provarespondida_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questoes',
            new_name='Questao',
        ),
        migrations.AddField(
            model_name='provarespondida',
            name='resposta',
            field=models.CharField(default=2, max_length=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProvaCompleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=3)),
                ('acertos', models.IntegerField()),
                ('respostas', models.ManyToManyField(default=None, null=True, to='materiais.provarespondida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
