# Generated by Django 4.2.4 on 2023-08-21 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0006_rename_questoes_questao_provarespondida_resposta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provacompleta',
            name='respostas',
            field=models.ManyToManyField(to='materiais.provarespondida'),
        ),
        migrations.AlterField(
            model_name='provarespondida',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='materiais.questao'),
        ),
    ]
