# Generated by Django 4.2.4 on 2023-08-21 02:30

from django.db import migrations, models
import django.db.models.deletion
import materiais.funcs


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0007_alter_provacompleta_respostas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='submateria',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='opcoes',
        ),
        migrations.AddField(
            model_name='questao',
            name='sub_materia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='materiais.submateria'),
        ),
        migrations.AddField(
            model_name='submateria',
            name='materia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='materiais.materia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questao',
            name='imagem',
            field=models.ImageField(null=True, upload_to=materiais.funcs.define_image_path),
        ),
        migrations.AlterField(
            model_name='questao',
            name='nivel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='materiais.nivel'),
        ),
    ]
