# Generated by Django 4.2.4 on 2023-08-21 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0008_remove_materia_submateria_remove_questao_materia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submateria',
            name='materia',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='materiais.materia'),
        ),
    ]
