# Generated by Django 4.2.4 on 2023-08-21 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0009_alter_submateria_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='sub_materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='materiais.submateria'),
        ),
    ]
