# Generated by Django 4.2.4 on 2023-08-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0009_remove_provacompleta_materias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=70)),
            ],
        ),
        migrations.RemoveField(
            model_name='provacompleta',
            name='tipos',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='tipo',
        ),
    ]
