# Generated by Django 4.2.4 on 2023-08-27 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0010_simulado_remove_provacompleta_tipos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provarespondida',
            name='simulado',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='materiais.simulado'),
        ),
        migrations.AddField(
            model_name='simulado',
            name='materia',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='materiais.materia'),
        ),
    ]
