# Generated by Django 4.2.4 on 2023-08-21 02:51

from django.db import migrations, models
import materiais.funcs


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0010_conteudo_sub_materia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='sub_materia',
        ),
        migrations.AlterField(
            model_name='questao',
            name='imagem',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=materiais.funcs.define_image_path),
        ),
    ]
