# Generated by Django 4.2.4 on 2023-08-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0011_remove_questao_sub_materia_alter_questao_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provacompleta',
            name='tipo',
        ),
        migrations.AddField(
            model_name='provacompleta',
            name='nota',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questao',
            name='tipo',
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='provacompleta',
            name='acertos',
            field=models.IntegerField(default=0),
        ),
    ]
