# Generated by Django 4.2.4 on 2023-08-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0012_remove_provacompleta_tipo_provacompleta_nota_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questoesprova',
            options={'verbose_name_plural': 'Questoes pra prova'},
        ),
        migrations.AlterModelOptions(
            name='submateria',
            options={'verbose_name_plural': 'Sub Materias'},
        ),
        migrations.AddField(
            model_name='provacompleta',
            name='erros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='provacompleta',
            name='ranking_melhores_conteudos',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='provacompleta',
            name='ranking_piores_conteudos',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='provacompleta',
            name='tipo',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='questao',
            name='tipo',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
