# Generated by Django 4.2.4 on 2023-08-22 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0012_remove_provacompleta_tipo_provacompleta_nota_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='questoesprova',
            options={'verbose_name_plural': 'Questoes pra prova'},
        ),
        migrations.AlterModelOptions(
            name='submateria',
            options={'verbose_name_plural': 'Sub Materias'},
        ),
        migrations.RemoveField(
            model_name='questao',
            name='tipo',
        ),
        migrations.AddField(
            model_name='provacompleta',
            name='erros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='provacompleta',
            name='ranking_melhores_conteudos',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='provacompleta',
            name='ranking_piores_conteudos',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='questao',
            name='conteudo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='materiais.conteudo'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='opcao_correta',
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='questoesprova',
            name='tipo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='materiais.tipo'),
        ),
    ]
