# Generated by Django 4.2.4 on 2023-08-22 19:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0013_tipo_alter_questoesprova_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questoesprova',
            name='tipo',
        ),
        migrations.AddField(
            model_name='provacompleta',
            name='data_feita',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provacompleta',
            name='tipos',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='questao',
            name='tipo',
            field=models.CharField(blank=True, choices=[('linguagens', 'Linguagens e suas Tecnologias'), ('matematica', 'Matemática e suas Tecnologias'), ('natureza', 'Ciências da Natureza'), ('humanas', 'Ciências Humanas')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='provacompleta',
            name='nota',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='provarespondida',
            name='acerto',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
