# Generated by Django 4.2.4 on 2023-08-22 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0013_alter_questoesprova_options_alter_submateria_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='tipo',
        ),
    ]
