# Generated by Django 4.2.4 on 2023-08-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0014_remove_questoesprova_tipo_provacompleta_data_feita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provacompleta',
            name='acerto_dificuldade',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='questao',
            name='opcoes',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='provacompleta',
            name='tipos',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='questao',
            name='opcao_correta',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='QuestoesProva',
        ),
    ]
