# Generated by Django 4.2.4 on 2023-08-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0014_remove_questao_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
            ],
        ),
    ]
