# Generated by Django 4.2.4 on 2023-08-22 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0015_tipos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tipos',
            new_name='Tipo',
        ),
    ]
