# Generated by Django 4.2.4 on 2023-08-22 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0016_rename_tipos_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='materiais.tipo'),
            preserve_default=False,
        ),
    ]
